name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.3'
            rails: '~> 7.0'
          - ruby: '4.0'
            rails: '~> 7.0'
          - ruby: '4.0'
            rails: '~> 8.0'
          - ruby: 'ruby-head'
            rails: '~> 8.0'
    name: Test with Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    env:
      RAILS_GEM_VERSION: "${{ matrix.rails }}"
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 && bundle show
      - name: Test with Rake
        run: bundle exec rake
